### ISSUE TITLE
Example usage has unnecessary invocation of rice.

### ISSUE THREAD

**Issue by jamie-at-sas** [Matir/sshdog#3]
Example usage text includes this line:

% rice append --exec sshdog

However, if that is done, get this output

no calls to rice.FindBox() or rice.MustFindBox() found in import path `github.com/Matir/sshdog`

So it is a no-op.

**Comment by Matir** [comment]
That is strange, I don't know if rice has changed their API, as there's decidedly a call (to `rice.Config.FindBox` to be precise): https://github.com/Matir/sshdog/blob/master/sshdog.go#L103

**Comment by Matir** [comment]
Ah, apparently it's related to this issue in rice: https://github.com/GeertJohan/go.rice/issues/58

I'll create a fix with their workaround, thanks for bringing it to my attention!
